### ISSUE TITLE
KeyError: 'subdomains'

### ISSUE THREAD

**Issue by bcoles** [si9int/Acamar#4]
```
[!] Enumerating threadcrowd.com
	 - proceeding JSON output
Traceback (most recent call last):
  File "acamar.py", line 306, in <module>
    f()
  File "acamar.py", line 204, in enumThreatcrowd
    for e in j['subdomains']:
KeyError: 'subdomains'
```

**Comment by si9int** [comment]
This shouldn't be the case (normally). What was the domain you proceeded?
KeyError => no output was received for that domain on threadcrowd.com

**Comment by bcoles** [comment]
Agreed that it shouldn't happen. I don't remember exactly which domain it was.

Presumably malformed JSON was returned. Several of the methods don't catch `except KeyError:`. It would be a good idea to add error handling, in the event that the APIs are modified in the future, or in the event of temporary server error.

**Comment by bcoles** [comment]
Here's one:

```
$ curl https://threatcrowd.org/searchApi/v2/domain/report/?domain=sbosnet.nl
{"response_code":"0"}
```
